
package com.mapapi.wsdl;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CountriesPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountriesPort {


    /**
     * 
     * @param createCountryRequest
     * @return
     *     returns com.mapapi.wsdl.CreateCountryResponse
     */
    @WebMethod
    @WebResult(name = "createCountryResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "createCountryResponse")
    public CreateCountryResponse createCountry(
        @WebParam(name = "createCountryRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "createCountryRequest")
        CreateCountryRequest createCountryRequest);

    /**
     * 
     * @param getCountryByIdRequest
     */
    @WebMethod
    @Oneway
    public void getCountryById(
        @WebParam(name = "getCountryByIdRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getCountryByIdRequest")
        GetCountryByIdRequest getCountryByIdRequest);

}
