
package com.ajm.spring.rest.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "countryPort", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CountryPort {


    /**
     * 
     * @param getCountryRequest
     * @return
     *     returns com.ajm.spring.rest.wsdl.GetCountryResponse
     */
    @WebMethod
    @WebResult(name = "getCountryResponse", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "getCountryResponse")
    public GetCountryResponse getCountry(
        @WebParam(name = "getCountryRequest", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "getCountryRequest")
        GetCountryRequest getCountryRequest);

    /**
     * 
     * @param updateCountryRequest
     * @return
     *     returns com.ajm.spring.rest.wsdl.UpdateCountryResponse
     */
    @WebMethod
    @WebResult(name = "updateCountryResponse", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "updateCountryResponse")
    public UpdateCountryResponse updateCountry(
        @WebParam(name = "updateCountryRequest", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "updateCountryRequest")
        UpdateCountryRequest updateCountryRequest);

    /**
     * 
     * @param getAllCountriesRequest
     * @return
     *     returns com.ajm.spring.rest.wsdl.GetAllCountriesResponse
     */
    @WebMethod
    @WebResult(name = "getAllCountriesResponse", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "getAllCountriesResponse")
    public GetAllCountriesResponse getAllCountries(
        @WebParam(name = "getAllCountriesRequest", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "getAllCountriesRequest")
        GetAllCountriesRequest getAllCountriesRequest);

    /**
     * 
     * @param deleteCountryRequest
     * @return
     *     returns com.ajm.spring.rest.wsdl.DeleteCountryResponse
     */
    @WebMethod
    @WebResult(name = "deleteCountryResponse", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "deleteCountryResponse")
    public DeleteCountryResponse deleteCountry(
        @WebParam(name = "deleteCountryRequest", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "deleteCountryRequest")
        DeleteCountryRequest deleteCountryRequest);

    /**
     * 
     * @param createCountryRequest
     * @return
     *     returns com.ajm.spring.rest.wsdl.CreateCountryResponse
     */
    @WebMethod
    @WebResult(name = "createCountryResponse", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "createCountryResponse")
    public CreateCountryResponse createCountry(
        @WebParam(name = "createCountryRequest", targetNamespace = "http://com.ajm.soap.gen/gs-producing-web-service", partName = "createCountryRequest")
        CreateCountryRequest createCountryRequest);

}
