# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Cartographer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Cartographer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x43\x61rtographer.proto\x12\x0f\x63\x61rtographerspb\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x15\x43\x61rtographerIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x17\x43\x61rtographerNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"~\n\x14\x43\x61rtographerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"q\n\x1a\x43reateCartographerResponse\x12\x15\n\rsuccess_count\x18\x01 \x01(\x05\x12<\n\rcartographers\x18\x02 \x03(\x0b\x32%.cartographerspb.CartographerResponse\"G\n\x19\x43reateCartographerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ompany\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x32\xce\x02\n\x13\x43\x61rtographerService\x12X\n\x07GetById\x12&.cartographerspb.CartographerIdRequest\x1a%.cartographerspb.CartographerResponse\x12p\n\x13\x43reateCartographers\x12*.cartographerspb.CreateCartographerRequest\x1a+.cartographerspb.CreateCartographerResponse(\x01\x12k\n\x16GetCartographersByName\x12(.cartographerspb.CartographerNameRequest\x1a%.cartographerspb.CartographerResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Cartographer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTOGRAPHERIDREQUEST']._serialized_start=72
  _globals['_CARTOGRAPHERIDREQUEST']._serialized_end=107
  _globals['_CARTOGRAPHERNAMEREQUEST']._serialized_start=109
  _globals['_CARTOGRAPHERNAMEREQUEST']._serialized_end=148
  _globals['_CARTOGRAPHERRESPONSE']._serialized_start=150
  _globals['_CARTOGRAPHERRESPONSE']._serialized_end=276
  _globals['_CREATECARTOGRAPHERRESPONSE']._serialized_start=278
  _globals['_CREATECARTOGRAPHERRESPONSE']._serialized_end=391
  _globals['_CREATECARTOGRAPHERREQUEST']._serialized_start=393
  _globals['_CREATECARTOGRAPHERREQUEST']._serialized_end=464
  _globals['_CARTOGRAPHERSERVICE']._serialized_start=467
  _globals['_CARTOGRAPHERSERVICE']._serialized_end=801
# @@protoc_insertion_point(module_scope)
